In [3]:
import torch

In [4]:
x = torch.arange(12)

In [5]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
torch.randn(33, 43)

tensor([[ 1.1400,  0.9492, -2.6977,  ...,  1.0845, -1.1726,  1.0701],
        [-1.0345, -0.3099,  0.7798,  ..., -0.6042, -0.0533,  0.7324],
        [ 1.0844,  0.4863,  1.7612,  ...,  0.6988,  1.7535, -0.3196],
        ...,
        [ 0.8838,  0.4216,  0.7271,  ..., -0.3402, -1.8263,  0.0061],
        [-1.0117,  0.4469, -0.0202,  ..., -0.1150, -0.6122,  0.7773],
        [ 1.3153, -0.5318,  0.4445,  ..., -0.1140, -0.3814,  1.8973]])

In [15]:
a = [[1,2,3],[4,5,6], [7,8,9]]

In [17]:
b = torch.tensor(a)

In [22]:
b = b.reshape(-1)

In [25]:
b=b.reshape(3,-1)

In [36]:
b[2]

tensor([7, 8, 9])

In [38]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [40]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [41]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [66]:
a = torch.arange(24).reshape((1,-1))
b = torch.arange(48).reshape((-1, 1))
a, b

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
          18, 19, 20, 21, 22, 23]]),
 tensor([[ 0],
         [ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12],
         [13],
         [14],
         [15],
         [16],
         [17],
         [18],
         [19],
         [20],
         [21],
         [22],
         [23],
         [24],
         [25],
         [26],
         [27],
         [28],
         [29],
         [30],
         [31],
         [32],
         [33],
         [34],
         [35],
         [36],
         [37],
         [38],
         [39],
         [40],
         [41],
         [42],
         [43],
         [44],
         [45],
         [46],
         [47]]))

In [67]:
a+b

tensor([[ 0,  1,  2,  ..., 21, 22, 23],
        [ 1,  2,  3,  ..., 22, 23, 24],
        [ 2,  3,  4,  ..., 23, 24, 25],
        ...,
        [45, 46, 47,  ..., 66, 67, 68],
        [46, 47, 48,  ..., 67, 68, 69],
        [47, 48, 49,  ..., 68, 69, 70]])

In [63]:
a.shape

torch.Size([1, 24])

In [64]:
b.shape

torch.Size([1, 48])

In [77]:
a = torch.arange(12).reshape((2, -1))
b = torch.arange(24).reshape((-1, 2))
a, b

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]),
 tensor([[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15],
         [16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]))

In [80]:
a.shape

torch.Size([2, 6])

In [81]:
b.shape

torch.Size([12, 2])

### 